### Here are tests for all routes of the API. Take a look at https://marketplace.visualstudio.com/items?itemName=humao.rest-client for more information on how to use this file.
@port = {{$dotenv PORT}}
@baseUrl = http://localhost:{{port}}/api

### Register/Login a user
# @name postUsers
POST {{baseUrl}}/users HTTP/1.1
Content-Type: application/json

{
    "username": "lmachens"
}

### Update hidden marker ids
@markerId = {{getMarkers.response.body.$[0]._id}}

PATCH {{baseUrl}}/users/{{postUsers.request.body.username}} HTTP/1.1
Content-Type: application/json

{
    "hiddenMarkerIds": ["{{markerId}}"]
}


### Get markers
# @name getMarkers
GET {{baseUrl}}/markers HTTP/1.1
Accept: application/json


### Insert a marker
# @name insertMarker
POST {{baseUrl}}/markers HTTP/1.1
Content-Type: application/json

{
    "type": "fish_hotspot3",
    "position": [9405.321, 8984.482],
    "username": "{{postUsers.request.body.username}}"
}

### Delete a single marker
DELETE {{baseUrl}}/markers/{{insertMarker.response.body._id}} HTTP/1.1
Content-Type: application/json

{
    "userId": "{{postUsers.response.body._id}}"
}


### Get comments
# @name getComments
@markerId = {{getMarkers.response.body.$[0]._id}}

GET {{baseUrl}}/markers/{{markerId}}/comments HTTP/1.1
Accept: application/json

### Insert a comment
# @name insertComment
@markerId = {{getMarkers.response.body.$[0]._id}}
POST {{baseUrl}}/markers/{{markerId}}/comments HTTP/1.1
Content-Type: application/json

{
    "username": "[Coach] Leon",
    "message": "This is a test comment"
}

### POST a marker route
POST {{baseUrl}}/marker-routes HTTP/1.1
Content-Type: application/json

{
    "name": "Essences Route",
    "username": "system",
    "positions": [[8455.411, 8984.482], [8460.411, 8984.482], [8470.411, 8950.482]],
    "markersByType": {
        "essences_blightroot": 10,
        "essences_lightning_beetle": 10
    }
}

### GET all marker routes
GET {{baseUrl}}/marker-routes HTTP/1.1
Accept: application/json




