name: Build Overwolf Production App CI

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
      - run: npm install
      - name: Build Overwolf app
        env:
          VITE_API_ENDPOINT: ${{ secrets.VITE_API_ENDPOINT }}
          VITE_PLAUSIBLE_DOMAIN: ${{ secrets.VITE_PLAUSIBLE_DOMAIN }}
          VITE_PLAUSIBLE_API_HOST: 'https://apps.machens.dev'
        run: npm run build -- --filter=overwolf
      - name: Release Overwolf app
        env:
          OW_CLI_EMAIL: ${{ secrets.OW_CLI_EMAIL }}
          OW_CLI_API_KEY: ${{ secrets.OW_CLI_API_KEY }}
        run: npm run release
